### ISSUE TITLE
godoc 问题

### ISSUE THREAD

**Issue by lixiangzhong** [b3log/gulu#1]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/gulu)搜寻资料解决问题。

----

### 描述问题

guluFile 首字母小写,godoc 不识别他的methods,没办法直接看文档来快速上手

### 重现步骤

请描述如何重现这个问题。

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 平台环境和版本

- OS: [e.g. windows, mac, linux]
- Version [e.g. 1.0.0]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
收到，godoc 相关问题稍后改进，感谢反馈！

**Comment by 88250** [comment]
https://godoc.org/github.com/b3log/gulu
